In [3]:
from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi
import pandas as pd

In [4]:
df = pd.read_csv('EasyVisa.csv')

In [5]:
df.head()

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified

In [7]:
data = df.to_dict(orient='records')

In [12]:
DB_NAME = 'US_VISA'
COLLECTION_NAME = 'visa_data'
CONNECTION_URL = "mongodb+srv://nithishkukutapu:c6CRHT7fGobBEFGr@cluster0.hbbgj9u.mongodb.net/?appName=Cluster0"

In [13]:
def get_mongo_client():
    # Create a new client and connect to the server
    client = MongoClient(CONNECTION_URL, server_api=ServerApi('1'))
    
    # Send a ping to confirm a successful connection
    try:
        client.admin.command('ping')
        print("Pinged your deployment. You successfully connected to MongoDB!")
    except Exception as e:
        print(e)
    return client

In [15]:
client = get_mongo_client()
database = client[DB_NAME]
collection = database[COLLECTION_NAME]
rec = collection.insert_many(data)

Pinged your deployment. You successfully connected to MongoDB!

In [18]:
records = collection.find()

In [23]:
# for i,j in enumerate(records):
#     print(f'{i}:{j}')

In [24]:
df = pd.DataFrame(list(collection.find()))

In [25]:
df

,_id,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,699ea9f34a802bc672b6dd58,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,699ea9f34a802bc672b6dd59,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,699ea9f34a802bc672b6dd5a,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,699ea9f34a802bc672b6dd5b,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,699ea9f34a802bc672b6dd5c,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...,...
25475,699ea9f34a802bc672b740db,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,699ea9f34a802bc672b740dc,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,699ea9f34a802bc672b740dd,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,699ea9f34a802bc672b740de,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,699ea9f34a802bc672b740df,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified